### ISSUE TITLE
photo

### ISSUE THREAD

**Issue by datatalking** [fusionbox/django-darkknight#13]
I'm interested in using this for my django app but where do you have photos or screenshots of what this looks like... I'm eager to give you a star

**Comment by gavinwahl** [comment]
Sure,

![form](https://user-images.githubusercontent.com/421710/38749713-d6d7b4f0-3f0f-11e8-8629-32573a0e6579.png)
![csr](https://user-images.githubusercontent.com/421710/38749719-da9b3a94-3f0f-11e8-8182-62a78674c007.png)
